language: node
os: linux
dist: xenial
node_js: 12

cache: npm

services:
  - docker

install:
  - npm ci

script:
  - docker build -t michaelilyin/index:latest .

before_deploy:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

deploy:
  - provider: script
    script: bash publish.sh
    on:
      branch: master

  - provider: script
    script: bash deploy.sh
    on:
      branch: master